<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    //get product label helper
    $productLabelHelper = $this->helper(Sparsh\ProductLabel\Helper\ProductLabelHelper::class);
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */
    $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */
            '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */
            $mode ?> <?= /* @noEscape */
            $mode ?>">
                <ol class="product-items <?= /* @noEscape */
                $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?= /* @noEscape */
                        ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <?php
                            //if there is product label found then display label
                            $_product = $_item;
                            $productLabelType = $productLabelHelper->getProductLabelType($_product);
                            if (!empty($productLabelType)) {
                                if ($productLabelType == 'text') {
                                    $productLabel = $productLabelHelper->getProductLabel($_product);
                                    $productLabelColor = $productLabelHelper->getProductLabelColor($_product);
                                    $productLabelBackgroundColor = $productLabelHelper->getProductLabelBackgroundColor($_product);
                                    $productLabelShape = $productLabelHelper->getProductLabelShape($_product);
                                    if ($productLabel && $productLabelShape) { ?>
                                        <span class="sparsh-product-label"
                                            <?= !empty($productLabelColor) ? 'data-color=' . /* @noEscape */ $productLabelColor : ''; ?> <?= !empty($productLabelBackgroundColor) ? 'data-background-color=' . /* @noEscape */ $productLabelBackgroundColor : ''; ?> <?= !empty($productLabelShape) ? 'data-shape=' . /* @noEscape */ $productLabelShape : '' ?>>
                                    <?= $block->escapeHtml($productLabel); ?>
                                </span>
                                    <?php }
                                } elseif ($productLabelType == 'image') {
                                    $productLabelImage = $productLabelHelper->getProductLabelImage($_product);
                                    if ($productLabelImage) { ?>
                                        <div class="sparsh-product-label-image">
                                            <img src="<?= /* @noEscape */ $productLabelHelper->getProductMediaUrl() . $productLabelImage; ?>">
                                        </div>
                                    <?php }
                                }
                            }
                            ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?= $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}'
                                                                type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <?php
                                                        $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @noEscape */
                                                                $postData ?>' type="button"
                                                                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else : ?>
                                                    <?php if ($_item->getIsSalable()) : ?>
                                                        <div class="stock available">
                                                            <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable">
                                                            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */
                                                        $block->getAddToWishlistParams($_item) ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?= /* @noEscape */ __('Add to Wish List') ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                    <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class); ?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */
                                                    $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?= /* @noEscape */ __('Add to Compare') ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <?php if (!empty($productLabelHelper->getProductLabelType($_item))) {
                                if ($productLabelHelper->getProductLabelType($_item) == 'image' && $productLabelHelper->getProductLabelImage($_item)) { ?>
                                    <div class="sparsh-product-label-image">
                                        <img src="<?= /* @noEscape */ $productLabelHelper->getProductMediaUrl() . /* @noEscape */ $productLabelHelper->getProductLabelImage($_item); ?>">
                                    </div>
                                <?php }
}
                            ?>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif; ?>
<script type="text/javascript">
    require(['jquery'],function($) {
        $(document).ready(function() {
            //loop through all the labels found
            $('.sparsh-product-label').each(function(index) {
                //set default background color & font color
                if($(this).attr('data-background-color')){
                    $(this).css("background-color", $(this).attr('data-background-color'));
                }else{
                    $(this).css("background-color", '#ff0000');
                }
                if($(this).attr('data-color')){
                    $(this).css("color", $(this).attr('data-color'));
                }else{
                    $(this).css("color", '#ffffff');
                }

                //assign css according to shapes found
                if($(this).attr('data-shape')){
                    $(this).addClass($(this).attr('data-shape'));
                }
            });
        });
    });
</script>

